# ---------------------------------------------------------------------------- #
#                                 LOCKUP CONFIG                                #
# ---------------------------------------------------------------------------- #

[profile.default]
  extends = "../foundry.base.toml"
  optimizer_runs = 500
  remappings = [
    "@chainlink/=node_modules/@chainlink/",
    "@openzeppelin/=node_modules/@openzeppelin/",
    "@prb/=node_modules/@prb/",
    "@sablier/=node_modules/@sablier/",
    "forge-std/=node_modules/forge-std/",
    "solarray/=node_modules/solarray/",
    "solady/=node_modules/solady/",
  ]

[profile.default.fuzz]
  runs = 50

[profile.default.invariant]
  depth = 20
  runs = 20

[profile.lite]
  extends = "../foundry.base.toml"

[profile.optimized]
  extends = "../foundry.base.toml"
  test = "tests/mocks"

[profile.test-optimized]
  extends = "../foundry.base.toml"
