# ---------------------------------------------------------------------------- #
#                                 LOCKUP CONFIG                                #
# ---------------------------------------------------------------------------- #

[profile.default]
  extends = "../foundry.toml"
  optimizer_runs = 500
  remappings = [
    "solarray/=../node_modules/solarray/",
  ]

[profile.default.fuzz]
  runs = 50

[profile.lite]
  extends = "../foundry.toml"

[profile.optimized]
  extends = "../foundry.toml"
  test = "tests/mocks"

[profile.test-optimized]
  extends = "../foundry.toml"

[lint]
  lint_on_build = false
