// SPDX-License-Identifier: GPL-3.0-or-later
pragma solidity >=0.8.22;

import { IERC20 } from "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import { AggregatorV3Interface } from "@chainlink/contracts/src/v0.8/shared/interfaces/AggregatorV3Interface.sol";
import { IERC20Metadata } from "@openzeppelin/contracts/token/ERC20/extensions/IERC20Metadata.sol";
import { SafeERC20 } from "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";
import { SafeCast } from "@openzeppelin/contracts/utils/math/SafeCast.sol";
import { IERC165 } from "@openzeppelin/contracts/utils/introspection/IERC165.sol";
import { ReentrancyGuard } from "@openzeppelin/contracts/utils/ReentrancyGuard.sol";
import { Strings } from "@openzeppelin/contracts/utils/Strings.sol";
import { Batch } from "@sablier/evm-utils/src/Batch.sol";
import { SafeOracle } from "@sablier/evm-utils/src/libraries/SafeOracle.sol";
import { SafeTokenSymbol } from "@sablier/evm-utils/src/libraries/SafeTokenSymbol.sol";
import { Comptrollerable } from "@sablier/evm-utils/src/Comptrollerable.sol";
import { ISablierComptroller } from "@sablier/evm-utils/src/interfaces/ISablierComptroller.sol";

import { SablierBobState } from "./abstracts/SablierBobState.sol";
import { BobVaultShare } from "./BobVaultShare.sol";
import { IBobVaultShare } from "./interfaces/IBobVaultShare.sol";
import { ISablierBob } from "./interfaces/ISablierBob.sol";
import { ISablierBobAdapter } from "./interfaces/ISablierBobAdapter.sol";
import { Errors } from "./libraries/Errors.sol";
import { Bob } from "./types/Bob.sol";

/*

███████╗ █████╗ ██████╗ ██╗     ██╗███████╗██████╗     ██████╗  ██████╗ ██████╗
██╔════╝██╔══██╗██╔══██╗██║     ██║██╔════╝██╔══██╗    ██╔══██╗██╔═══██╗██╔══██╗
███████╗███████║██████╔╝██║     ██║█████╗  ██████╔╝    ██████╔╝██║   ██║██████╔╝
╚════██║██╔══██║██╔══██╗██║     ██║██╔══╝  ██╔══██╗    ██╔══██╗██║   ██║██╔══██╗
███████║██║  ██║██████╔╝███████╗██║███████╗██║  ██║    ██████╔╝╚██████╔╝██████╔╝
╚══════╝╚═╝  ╚═╝╚═════╝ ╚══════╝╚═╝╚══════╝╚═╝  ╚═╝    ╚═════╝  ╚═════╝ ╚═════╝

*/

/// @title SablierBob
/// @notice See the documentation in {ISablierBob}.
contract SablierBob is
    Batch, // 1 inherited component
    Comptrollerable, // 1 inherited component
    ISablierBob, // 2 inherited components
    ReentrancyGuard, // 1 inherited component
    SablierBobState // 1 inherited component
{
    using SafeCast for uint256;
    using SafeERC20 for IERC20;
    using SafeTokenSymbol for address;
    using Strings for uint256;

    /*//////////////////////////////////////////////////////////////////////////
                                     MODIFIERS
    //////////////////////////////////////////////////////////////////////////*/

    /// @dev Modifier to check that the vault is active.
    modifier onlyActive(uint256 vaultId) {
        _revertIfSettledOrExpired(vaultId);
        _;
    }

    /*//////////////////////////////////////////////////////////////////////////
                                    CONSTRUCTOR
    //////////////////////////////////////////////////////////////////////////*/

    /// @param initialComptroller The address of the initial comptroller contract.
    constructor(address initialComptroller) Comptrollerable(initialComptroller) SablierBobState() { }

    /*//////////////////////////////////////////////////////////////////////////
                          USER-FACING READ-ONLY FUNCTIONS
    //////////////////////////////////////////////////////////////////////////*/

    /// @inheritdoc ISablierBob
    function calculateMinFeeWei(uint256 vaultId) external view override notNull(vaultId) returns (uint256 minFeeWei) {
        // Return 0 if the vault has an adapter, since the fee is taken from yield generated by the adapter.
        if (address(_vaults[vaultId].adapter) != address(0)) {
            return 0;
        }

        // Calculate the minimum fee in wei for the Bob protocol.
        minFeeWei = comptroller.calculateMinFeeWei({ protocol: ISablierComptroller.Protocol.Bob });
    }

    /*//////////////////////////////////////////////////////////////////////////
                        USER-FACING STATE-CHANGING FUNCTIONS
    //////////////////////////////////////////////////////////////////////////*/

    /// @inheritdoc ISablierBob
    function createVault(
        IERC20 token,
        AggregatorV3Interface oracle,
        uint40 expiry,
        uint128 targetPrice
    )
        external
        override
        returns (uint256 vaultId)
    {
        // Check: token is not the zero address.
        if (address(token) == address(0)) {
            revert Errors.SablierBob_TokenAddressZero();
        }

        // Check: token is not the native token placeholder.
        if (address(token) == NATIVE_TOKEN_PLACEHOLDER) {
            revert Errors.SablierBob_NativeTokenPlaceholderForbidden();
        }

        // Check: token is not the native token with ERC-20 interface.
        if (address(token) == nativeTokenWithERC20Interface) {
            revert Errors.SablierBob_ForbidNativeTokenWithERC20Interface(address(token));
        }

        // Retrieve token symbol and decimals from the ERC-20 contract.
        string memory tokenSymbol = address(token).safeTokenSymbol();
        uint8 tokenDecimals = IERC20Metadata(address(token)).decimals();

        // Create the vault with the provided parameters.
        vaultId = _createVault(token, oracle, expiry, targetPrice, tokenSymbol, tokenDecimals);
    }

    /// @inheritdoc ISablierBob
    function createVaultWithNativeToken(
        AggregatorV3Interface oracle,
        uint40 expiry,
        uint128 targetPrice,
        string memory tokenSymbol,
        uint8 tokenDecimals
    )
        external
        payable
        override
        returns (uint256 vaultId)
    {
        // Check: token symbol is not empty.
        if (bytes(tokenSymbol).length == 0) {
            revert Errors.SablierBob_TokenSymbolEmpty();
        }

        // Sanitize the token symbol.
        tokenSymbol = SafeTokenSymbol.sanitizedTokenSymbol(tokenSymbol);

        // Create the vault with the provided parameters.
        vaultId =
            _createVault(IERC20(NATIVE_TOKEN_PLACEHOLDER), oracle, expiry, targetPrice, tokenSymbol, tokenDecimals);
    }

    /// @inheritdoc ISablierBob
    function enter(
        uint256 vaultId,
        uint128 amount
    )
        external
        payable
        override
        nonReentrant
        notNull(vaultId)
        onlyActive(vaultId)
    {
        // Effect: sync the price from oracle.
        _syncPriceFromOracle(vaultId);

        // Check: the vault is still active after the price sync.
        _revertIfSettledOrExpired(vaultId);

        // Get the vault token.
        IERC20 token = _vaults[vaultId].token;
        bool isNativeVault = address(token) == NATIVE_TOKEN_PLACEHOLDER;

        // If its a native token vault, use the msg.value as the deposit amount.
        if (isNativeVault) {
            amount = msg.value.toUint128();
        }
        // Check: no native tokens sent for an ERC-20 vault.
        else if (msg.value > 0) {
            revert Errors.SablierBob_MsgValueNotZeroForERC20Vault();
        }

        // Check: the deposit amount is not zero.
        if (amount == 0) {
            revert Errors.SablierBob_DepositAmountZero(vaultId, msg.sender);
        }

        // Get the vault adapter.
        ISablierBobAdapter adapter = _vaults[vaultId].adapter;

        // Check if its a native token vault.
        if (isNativeVault) {
            if (address(adapter) != address(0)) {
                // Interaction: forward native tokens to the adapter using the adapter's {stake} function.
                adapter.stake{ value: amount }(vaultId, msg.sender, amount);
            } else {
                // Do nothing since amount is deposited via `msg.value`.
            }
        }
        // Otherwise, its an ERC-20 vault.
        else {
            if (address(adapter) != address(0)) {
                token.safeTransferFrom(msg.sender, address(adapter), amount);

                // Interaction: stake the tokens via the adapter.
                adapter.stake(vaultId, msg.sender, amount);
            } else {
                token.safeTransferFrom(msg.sender, address(this), amount);
            }
        }

        // Interaction: mint share tokens to the caller.
        _vaults[vaultId].shareToken.mint(vaultId, msg.sender, amount);

        // Log the deposit.
        emit Enter({ vaultId: vaultId, user: msg.sender, amountReceived: amount, sharesMinted: amount });
    }

    /// @inheritdoc ISablierBob
    function redeem(uint256 vaultId)
        external
        payable
        override
        nonReentrant
        notNull(vaultId)
        returns (uint128 transferAmount, uint128 feeAmountDeductedFromYield)
    {
        // If the vault is active, sync the price from the oracle to update the status.
        if (_statusOf(vaultId) == Bob.Status.ACTIVE) {
            // Effect: sync the price from oracle.
            _syncPriceFromOracle(vaultId);

            // If it's still active after the sync, revert.
            if (_statusOf(vaultId) == Bob.Status.ACTIVE) {
                revert Errors.SablierBob_VaultStillActive(vaultId);
            }

            // Otherwise, the vault has been settled.
        }

        // Cache storage variables.
        ISablierBobAdapter adapter = _vaults[vaultId].adapter;
        IBobVaultShare shareToken = _vaults[vaultId].shareToken;
        IERC20 token = _vaults[vaultId].token;
        bool isNativeVault = address(token) == NATIVE_TOKEN_PLACEHOLDER;

        // Get the caller's share balance.
        uint128 shareBalance = shareToken.balanceOf(msg.sender).toUint128();

        // Check: the share balance is not zero.
        if (shareBalance == 0) {
            revert Errors.SablierBob_NoSharesToRedeem(vaultId, msg.sender);
        }

        // Check if the vault has an adapter.
        if (address(adapter) != address(0)) {
            // Check: the deposit token is staked with the adapter.
            if (_vaults[vaultId].isStakedInAdapter) {
                // Interaction: unstake all tokens via the adapter.
                _unstakeFullAmountViaAdapter(vaultId, adapter);

                // Effect: set isStakedInAdapter to false.
                _vaults[vaultId].isStakedInAdapter = false;
            }

            // Interaction: Get the transfer amount and the fee deducted from yield.
            (transferAmount, feeAmountDeductedFromYield) =
                adapter.processTokenRedemption(vaultId, msg.sender, shareBalance);

            // Interaction: transfer the fee to the comptroller address.
            if (feeAmountDeductedFromYield > 0) {
                // If its a native token vault, forward native tokens to the comptroller.
                if (isNativeVault) {
                    (bool success,) = address(comptroller).call{ value: feeAmountDeductedFromYield }("");

                    // Ignore success check because a failed transfer to comptroller should not block redemption.
                    success;
                }
                // Otherwise, transfer ERC-20 tokens to the comptroller.
                else {
                    token.safeTransfer(address(comptroller), feeAmountDeductedFromYield);
                }
            }
        }
        // Otherwise, its an ERC-20 vault.
        else {
            // Get the minimum fee from the comptroller.
            ISablierComptroller comptroller_ = comptroller;
            uint256 minFeeWei = comptroller_.calculateMinFeeWei({ protocol: ISablierComptroller.Protocol.Bob });

            // If its an ERC-20 vault, check that `msg.value` is greater than or equal to the minimum fee.
            if (!isNativeVault) {
                // Check: `msg.value` is greater than or equal to the minimum fee.
                if (msg.value < minFeeWei) {
                    revert Errors.SablierBob_InsufficientFeePayment(msg.value, minFeeWei);
                }

                // Interaction: forward native token fee to comptroller.
                if (msg.value > 0) {
                    (bool success,) = address(comptroller_).call{ value: msg.value }("");
                    if (!success) {
                        revert Errors.SablierBob_NativeFeeTransferFailed();
                    }
                }

                // Return the transfer amount.
                transferAmount = shareBalance;
            }
            // Otherwise, its a native token vault, so deduct minFeeWei from transferAmount.
            else {
                transferAmount = shareBalance - uint128(minFeeWei);
            }
        }

        // Interaction: burn share tokens from the caller.
        shareToken.burn(vaultId, msg.sender, shareBalance);

        // Interaction: transfer tokens to the caller.
        if (isNativeVault) {
            (bool success,) = msg.sender.call{ value: transferAmount }("");
            if (!success) {
                revert Errors.SablierBob_NativeTokenTransferFailed();
            }
        } else {
            token.safeTransfer(msg.sender, transferAmount);
        }

        // Log the event.
        emit Redeem({
            vaultId: vaultId,
            user: msg.sender,
            amountReceived: transferAmount,
            sharesBurned: shareBalance,
            fee: feeAmountDeductedFromYield
        });
    }

    /// @inheritdoc ISablierBob
    function setNativeToken(address newNativeToken) external override onlyComptroller {
        // Check: provided token is not zero address.
        if (newNativeToken == address(0)) {
            revert Errors.SablierBob_NativeTokenZeroAddress();
        }

        // Check: native token is not already set.
        if (nativeTokenWithERC20Interface != address(0)) {
            revert Errors.SablierBob_NativeTokenAlreadySet(nativeTokenWithERC20Interface);
        }

        // Effect: set the native token with ERC-20 interface.
        nativeTokenWithERC20Interface = newNativeToken;

        // Log the update.
        emit SetNativeToken({ comptroller: msg.sender, nativeToken: newNativeToken });
    }

    /// @inheritdoc ISablierBob
    function setDefaultAdapter(IERC20 token, ISablierBobAdapter newAdapter) external override onlyComptroller {
        // Check: the new adapter implements the {ISablierBobAdapter} interface.
        if (address(newAdapter) != address(0)) {
            bytes4 interfaceId = type(ISablierBobAdapter).interfaceId;
            if (!IERC165(address(newAdapter)).supportsInterface(interfaceId)) {
                revert Errors.SablierBob_NewAdapterMissesInterface(address(newAdapter));
            }
        }

        // Effect: set the default adapter for the token.
        _defaultAdapters[token] = newAdapter;

        // Log the adapter change.
        emit SetDefaultAdapter(token, newAdapter);
    }

    /// @inheritdoc ISablierBob
    function syncPriceFromOracle(uint256 vaultId)
        external
        override
        nonReentrant
        notNull(vaultId)
        onlyActive(vaultId)
        returns (uint128 latestPrice)
    {
        // Effect: sync the price from oracle.
        latestPrice = _syncPriceFromOracle(vaultId);
    }

    /// @inheritdoc ISablierBob
    function unstakeTokensViaAdapter(uint256 vaultId)
        external
        override
        nonReentrant
        notNull(vaultId)
        returns (uint128 amountReceivedFromAdapter)
    {
        // Cache storage variable.
        ISablierBobAdapter adapter = _vaults[vaultId].adapter;

        // Check: the vault has an adapter.
        if (address(adapter) == address(0)) {
            revert Errors.SablierBob_VaultHasNoAdapter(vaultId);
        }

        // Check: the vault has not already been unstaked.
        if (!_vaults[vaultId].isStakedInAdapter) {
            revert Errors.SablierBob_VaultAlreadyUnstaked(vaultId);
        }

        // Check: there is something to unstake.
        if (adapter.getTotalYieldBearingTokenBalance(vaultId) == 0) {
            revert Errors.SablierBob_UnstakeAmountZero(vaultId);
        }

        // If the vault is active, sync the price from the oracle to update the status.
        if (_statusOf(vaultId) == Bob.Status.ACTIVE) {
            // Effect: sync the price from oracle.
            _syncPriceFromOracle(vaultId);

            // If it's still active after the sync, revert.
            if (_statusOf(vaultId) == Bob.Status.ACTIVE) {
                revert Errors.SablierBob_VaultStillActive(vaultId);
            }

            // Otherwise, the vault has been settled.
        }

        // Effect: mark the vault as not staked with the adapter.
        _vaults[vaultId].isStakedInAdapter = false;

        // Interaction: unstake all tokens via the adapter.
        amountReceivedFromAdapter = _unstakeFullAmountViaAdapter(vaultId, adapter);
    }

    /// @inheritdoc ISablierBob
    function onShareTransfer(
        uint256 vaultId,
        address from,
        address to,
        uint256 amount,
        uint256 fromBalanceBefore
    )
        external
        override
    {
        // Check: caller is the share token for this vault.
        if (msg.sender != address(_vaults[vaultId].shareToken)) {
            revert Errors.SablierBob_CallerNotShareToken(vaultId, msg.sender);
        }

        // Cache storage variable.
        ISablierBobAdapter adapter = _vaults[vaultId].adapter;
        if (address(adapter) != address(0)) {
            // Interaction: update staked token holding of the user in the adapter.
            adapter.updateStakedTokenBalance(vaultId, from, to, amount, fromBalanceBefore);
        }
    }

    /*//////////////////////////////////////////////////////////////////////////
                                      RECEIVE
    //////////////////////////////////////////////////////////////////////////*/

    /// @dev We need `receive` function to accept ETH from the adapter when native token vaults are used.
    receive() external payable { }

    /*//////////////////////////////////////////////////////////////////////////
                          PRIVATE STATE-CHANGING FUNCTIONS
    //////////////////////////////////////////////////////////////////////////*/

    /// @dev Private function to create a vault with the provided parameters.
    function _createVault(
        IERC20 token,
        AggregatorV3Interface oracle,
        uint40 expiry,
        uint128 targetPrice,
        string memory tokenSymbol,
        uint8 tokenDecimals
    )
        private
        returns (uint256 vaultId)
    {
        uint40 currentTimestamp = uint40(block.timestamp);

        // Check: expiry is in the future.
        if (expiry <= currentTimestamp) {
            revert Errors.SablierBob_ExpiryNotInFuture(expiry, currentTimestamp);
        }

        // Check: target price is not zero.
        if (targetPrice == 0) {
            revert Errors.SablierBob_TargetPriceZero();
        }

        // Check: oracle implements the Chainlink {AggregatorV3Interface} interface.
        uint128 latestPrice = SafeOracle.validateOracle(oracle);

        // Check: target price is greater than latest oracle price.
        if (targetPrice <= latestPrice) {
            revert Errors.SablierBob_TargetPriceTooLow(targetPrice, latestPrice);
        }

        // Load the vault ID from storage.
        vaultId = nextVaultId;

        // Effect: bump the next vault ID.
        unchecked {
            nextVaultId = vaultId + 1;
        }

        // Effect: deploy the share token for this vault.
        IBobVaultShare shareToken = new BobVaultShare({
            name_: string.concat("Sablier Bob ", tokenSymbol, " Vault #", vaultId.toString()),
            symbol_: string.concat(
                tokenSymbol,
                "-",
                uint256(targetPrice).toString(),
                "-",
                uint256(expiry).toString(),
                "-",
                vaultId.toString()
            ),
            decimals_: tokenDecimals,
            sablierBob: address(this),
            vaultId: vaultId
        });

        // Copy the adapter from storage to memory.
        ISablierBobAdapter adapter = _defaultAdapters[token];

        // Effect: create the vault.
        _vaults[vaultId] = Bob.Vault({
            token: token,
            expiry: expiry,
            lastSyncedAt: currentTimestamp,
            shareToken: shareToken,
            oracle: oracle,
            adapter: adapter,
            isStakedInAdapter: false,
            targetPrice: targetPrice,
            lastSyncedPrice: latestPrice
        });

        // Interaction: register the vault with the adapter.
        if (address(adapter) != address(0)) {
            adapter.registerVault({ vaultId: vaultId, isNative: address(token) == NATIVE_TOKEN_PLACEHOLDER });

            // Effect: mark the vault as staked in the adapter.
            _vaults[vaultId].isStakedInAdapter = true;
        }

        // Log the event.
        emit CreateVault(vaultId, token, oracle, adapter, shareToken, targetPrice, expiry);
    }

    /// @notice Private function that reverts if the vault is settled or expired.
    function _revertIfSettledOrExpired(uint256 vaultId) private view {
        if (_statusOf(vaultId) != Bob.Status.ACTIVE) {
            revert Errors.SablierBob_VaultNotActive(vaultId);
        }
    }

    /// @dev Private function to fetch the latest oracle price and update it in the vault storage.
    /// @param vaultId The ID of the vault.
    /// @return latestPrice The latest price from the oracle.
    function _syncPriceFromOracle(uint256 vaultId) private returns (uint128 latestPrice) {
        AggregatorV3Interface oracleAddress = _vaults[vaultId].oracle;

        // Get the latest price from the oracle with safety checks.
        (latestPrice,) = SafeOracle.safeOraclePrice(oracleAddress);

        // Return if the latest price is zero.
        if (latestPrice == 0) {
            return 0;
        }

        uint40 currentTimestamp = uint40(block.timestamp);

        // Effect: update the last synced price and timestamp.
        _vaults[vaultId].lastSyncedPrice = latestPrice;
        _vaults[vaultId].lastSyncedAt = currentTimestamp;

        // Log the event.
        emit SyncPriceFromOracle({
            vaultId: vaultId,
            oracle: oracleAddress,
            latestPrice: latestPrice,
            syncedAt: currentTimestamp
        });
    }

    /// @dev Private function to unstake all tokens using the adapter.
    /// @param vaultId The ID of the vault.
    /// @param adapter The adapter to use for unstaking.
    /// @return amountReceivedFromAdapter The amount of tokens received from the adapter after unstaking.
    function _unstakeFullAmountViaAdapter(
        uint256 vaultId,
        ISablierBobAdapter adapter
    )
        private
        returns (uint128 amountReceivedFromAdapter)
    {
        uint128 wrappedTokenUnstakedAmount;

        // Interaction: unstake all tokens via the adapter.
        (wrappedTokenUnstakedAmount, amountReceivedFromAdapter) = adapter.unstakeFullAmount(vaultId);

        // Log the event.
        emit UnstakeFromAdapter(vaultId, adapter, wrappedTokenUnstakedAmount, amountReceivedFromAdapter);
    }
}
