# ---------------------------------------------------------------------------- #
#                                 UTILS CONFIG                                 #
# ---------------------------------------------------------------------------- #

[profile.default]
  ast = true # Needed for upgrade safety validations by foundry-upgrades
  build_info = true # Needed for upgrade safety validations by foundry-upgrades
  extends = "../foundry.base.toml"
  extra_output = ["storageLayout"] # Needed for upgrade safety validations by foundry-upgrades
  ffi = true # Needed for upgrade safety validations by foundry-upgrades
  gas_reports = ["*"]
  optimizer_runs = 10_000
  remappings = [
    "@chainlink/=node_modules/@chainlink/",
    "@openzeppelin/=node_modules/@openzeppelin/",
    "@prb/=node_modules/@prb/",
    "@sablier/=node_modules/@sablier/",
    "forge-std/=node_modules/forge-std/",
    "solady/=node_modules/solady/",
  ]
  script = "scripts"

[profile.default.fuzz]
  runs = 1000

[profile.default.invariant]
  depth = 100
  runs = 200

[profile.lite]
  extends = "../foundry.base.toml"

[profile.optimized]
  extends = "../foundry.base.toml"
  optimizer_runs = 100_000_000

[profile.test-optimized]
  extends = "../foundry.base.toml"
