# ---------------------------------------------------------------------------- #
#                                 UTILS CONFIG                                 #
# ---------------------------------------------------------------------------- #

[profile.default]
  ast = true
  build_info = true
  extends = "../foundry.toml"
  extra_output = ["storageLayout"]
  ffi = true
  gas_reports = ["*"]
  optimizer_runs = 10_000
  script = "scripts"

[profile.default.fuzz]
  runs = 1000

[profile.default.invariant]
  depth = 100
  runs = 200

[profile.lite]
  extends = "../foundry.toml"

[profile.optimized]
  extends = "../foundry.toml"
  optimizer_runs = 100_000_000

[profile.test-optimized]
  extends = "../foundry.toml"

[doc]
  path = "utils"
