# ---------------------------------------------------------------------------- #
#                                AIRDROPS CONFIG                               #
# ---------------------------------------------------------------------------- #

[profile.default]
  extends = "../foundry.base.toml"
  optimizer_runs = 100_000_000
  remappings = [
    "@chainlink/=node_modules/@chainlink/",
    "@openzeppelin/=node_modules/@openzeppelin/",
    "@prb/=node_modules/@prb/",
    "@sablier/=node_modules/@sablier/",
    "forge-std/=node_modules/forge-std/",
    "murky/=node_modules/murky/",
    "solady/=node_modules/solady/",
  ]

[profile.default.fuzz]
  runs = 1000

[profile.default.invariant]
  depth = 20
  runs = 20

[profile.lite]
  extends = "../foundry.base.toml"

[profile.lite.fuzz]
  runs = 50

[profile.optimized]
  extends = "../foundry.base.toml"
  optimizer_runs = 1_000_000

[profile.test-optimized]
  extends = "../foundry.base.toml"

[doc]
  path = "airdrops"
