# ---------------------------------------------------------------------------- #
#                                AIRDROPS CONFIG                               #
# ---------------------------------------------------------------------------- #

[profile.default]
  extends = "../foundry.toml"
  optimizer_runs = 100_000_000
  remappings = [
    "murky/=../node_modules/murky/",
  ]

[profile.default.fuzz]
  runs = 1000

[profile.default.invariant]
  depth = 20
  runs = 20

[profile.lite]
  extends = "../foundry.toml"

[profile.lite.fuzz]
  runs = 50

[profile.optimized]
  extends = "../foundry.toml"
  optimizer_runs = 1_000_000

[profile.test-optimized]
  extends = "../foundry.toml"

[doc]
  path = "airdrops"
