# See https://github.com/sablier-labs/devkit/blob/main/just/evm.just
import "./node_modules/@sablier/devkit/just/evm.just"

# Run just --list to see all available commands
default:
  @just --list

deploy *args:
    FOUNDRY_PROFILE=optimized \
        forge script scripts/solidity/DeployDeterministicFactories.s.sol \
        -vvv --broadcast {{ args }}

deploy-non-deterministic *args:
    FOUNDRY_PROFILE=optimized \
        forge script scripts/solidity/DeployFactories.s.sol \
        -vvv --broadcast {{ args }}

# Run all code checks
full-check:
    just solhint-check
    just fmt-check
    just prettier-check

# Run all code fixes
full-write:
    just solhint-write
    just fmt-write
    just prettier-write
