name: "BB CI: Module (Reusable)"

on:
  workflow_call:
    inputs:
      exclude-invariant-tests:
        default: false
        required: false
        type: boolean
      exclude-unit-tests:
        default: false
        required: false
        type: boolean
      match-path-fork:
        default: "tests/fork/**/*.sol"
        required: false
        type: string
      match-path-integration:
        default: "tests/{integration,utils}/**/*.sol"
        required: false
        type: string
      match-path-invariant:
        default: "tests/invariant/**/*.sol"
        required: false
        type: string
      match-path-unit:
        default: "tests/unit/**/*.sol"
        required: false
        type: string
      module:
        description: "Module name (e.g., airdrops, flow, lockup, utils)"
        required: true
        type: string

jobs:
  build:
    uses: "sablier-labs/gha-utils/.github/workflows/forge-build.yml@main"
    with:
      cache-path: |
        ${{ inputs.module }}/cache
        ${{ inputs.module }}/node_modules
        ${{ inputs.module }}/out
        ${{ inputs.module }}/out-optimized
      foundry-version: "v1.4.4"
      name: "Build"
      working-directory: ${{ inputs.module }}

  test-fork:
    needs: ["build"]
    if: needs.build.outputs.cache-status != 'primary'
    uses: "./.github/workflows/bb-fork-forge-test.yml"
    secrets: inherit
    with:
      cache-path: |
        ${{ inputs.module }}/cache
        ${{ inputs.module }}/node_modules
        ${{ inputs.module }}/out
        ${{ inputs.module }}/out-optimized
      foundry-fuzz-runs: 20
      foundry-profile: "test-optimized"
      match-path: ${{ inputs.match-path-fork }}
      name: "Fork tests"
      working-directory: ${{ inputs.module }}

  test-integration:
    needs: ["build"]
    if: needs.build.outputs.cache-status != 'primary'
    uses: "./.github/workflows/bb-forge-test.yml"
    secrets: inherit
    with:
      cache-path: |
        ${{ inputs.module }}/cache
        ${{ inputs.module }}/node_modules
        ${{ inputs.module }}/out
        ${{ inputs.module }}/out-optimized
      foundry-profile: "test-optimized"
      match-path: ${{ inputs.match-path-integration }}
      name: "Integration tests"
      working-directory: ${{ inputs.module }}

  test-invariant:
    needs: ["build"]
    if: needs.build.outputs.cache-status != 'primary' && !inputs.exclude-invariant-tests
    uses: "./.github/workflows/bb-forge-test.yml"
    secrets: inherit
    with:
      cache-path: |
        ${{ inputs.module }}/cache
        ${{ inputs.module }}/node_modules
        ${{ inputs.module }}/out
        ${{ inputs.module }}/out-optimized
      foundry-profile: "test-optimized"
      match-path: ${{ inputs.match-path-invariant }}
      name: "Invariant tests"
      working-directory: ${{ inputs.module }}

  test-unit:
    needs: ["build"]
    if: needs.build.outputs.cache-status != 'primary' && !inputs.exclude-unit-tests
    uses: "./.github/workflows/bb-forge-test.yml"
    secrets: inherit
    with:
      cache-path: |
        ${{ inputs.module }}/cache
        ${{ inputs.module }}/node_modules
        ${{ inputs.module }}/out
        ${{ inputs.module }}/out-optimized
      foundry-profile: "test-optimized"
      match-path: ${{ inputs.match-path-unit }}
      name: "Unit tests"
      working-directory: ${{ inputs.module }}
