name: "CI: Airdrops"
run-name: "CI Airdrops :: ${{ github.event.head_commit.message || github.event.pull_request.title }}"

concurrency:
  cancel-in-progress: true
  group: ${{github.workflow}}-${{github.ref}}

on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/ci-airdrops.yml"
      - ".github/workflows/ci-module.yml"
      - "airdrops/**"
      - "foundry.base.toml"
      - "package.json"
  push:
    branches:
      - "main"
      - "staging"
    paths:
      - ".github/workflows/ci-airdrops.yml"
      - ".github/workflows/ci-module.yml"
      - "airdrops/**"
      - "foundry.base.toml"
      - "package.json"

jobs:
  ci:
    uses: "./.github/workflows/ci-module.yml"
    with:
      module: "airdrops"
      run-integration: true
      run-fork: true
      integration-fuzz-runs: 2000
      coverage-match-path: "airdrops/tests/{integration,unit}/**/*.sol"
    secrets:
      ROUTEMESH_API_KEY: ${{ secrets.ROUTEMESH_API_KEY }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
