name: "CI: Fork"

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 1 * *" # at 3:00 AM UTC on the 1st of every month

jobs:
  build:
    strategy:
      matrix:
        module: [airdrops, bob, flow, lockup, utils]
    uses: "sablier-labs/gha-utils/.github/workflows/forge-build.yml@main"
    with:
      cache-path: &cache-path |
        ${{ matrix.module }}/cache
        ${{ matrix.module }}/node_modules
        ${{ matrix.module }}/out
        ${{ matrix.module }}/out-optimized
      foundry-version: &foundry-version "v1.5.1"
      name: "Build"
      working-directory: ${{ matrix.module }}

  test-fork:
    needs: ["build"]
    secrets:
      ROUTEMESH_API_KEY: ${{ secrets.ROUTEMESH_API_KEY }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - module: airdrops
            match-path: "tests/fork/**/*.sol"
          - module: bob
            match-path: "tests/*/fork/**/*.sol"
          - module: flow
            match-path: "tests/fork/**/*.sol"
          - module: lockup
            match-path: "tests/fork/**/*.sol"
          - module: utils
            match-path: "tests/fork/**/*.sol"
    uses: "sablier-labs/gha-utils/.github/workflows/forge-test.yml@main"
    with:
      cache-path: *cache-path
      foundry-fuzz-runs: 100
      foundry-profile: "test-optimized"
      foundry-version: *foundry-version
      fuzz-seed: true
      match-path: ${{ matrix.match-path }}
      name: "Fork tests (${{ matrix.module }})"
      retry-attempts: 2
      working-directory: ${{ matrix.module }}
