name: "CI: Flow"
run-name: "CI Flow :: ${{ github.event.head_commit.message || github.event.pull_request.title }}"

concurrency:
  cancel-in-progress: true
  group: ${{github.workflow}}-${{github.ref}}

on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/ci-flow.yml"
      - ".github/workflows/ci-module.yml"
      - "flow/**"
      - "foundry.base.toml"
      - "package.json"
  push:
    branches:
      - "main"
      - "staging"
    paths:
      - ".github/workflows/ci-flow.yml"
      - ".github/workflows/ci-module.yml"
      - "flow/**"
      - "foundry.base.toml"
      - "package.json"

jobs:
  ci:
    uses: "./.github/workflows/ci-module.yml"
    with:
      module: "flow"
      bulloak-test-dir: "tests/integration"
      run-integration: true
      run-invariant: true
      run-fork: true
      integration-fuzz-runs: 10000
      invariant-depth: 100
      invariant-runs: 1000
      coverage-match-path: "flow/tests/integration/**/*.sol"
    secrets:
      ROUTEMESH_API_KEY: ${{ secrets.ROUTEMESH_API_KEY }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
