name: "CI: Lockup"
run-name: "CI Lockup :: ${{ github.event.head_commit.message || github.event.pull_request.title }}"

concurrency:
  cancel-in-progress: true
  group: ${{github.workflow}}-${{github.ref}}

on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/ci-lockup.yml"
      - ".github/workflows/ci-module.yml"
      - "lockup/**"
      - "foundry.base.toml"
      - "package.json"
  push:
    branches:
      - "main"
      - "staging"
    paths:
      - ".github/workflows/ci-lockup.yml"
      - ".github/workflows/ci-module.yml"
      - "lockup/**"
      - "foundry.base.toml"
      - "package.json"

jobs:
  ci:
    uses: "./.github/workflows/ci-module.yml"
    with:
      module: "lockup"
      run-unit: true
      run-integration: true
      run-invariant: true
      run-fork: true
      coverage-match-path: "lockup/tests/{integration,unit}/**/*.sol"
    secrets:
      ROUTEMESH_API_KEY: ${{ secrets.ROUTEMESH_API_KEY }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
