name: "CI: Utils"
run-name: "CI Utils :: ${{ github.event.head_commit.message || github.event.pull_request.title }}"

concurrency:
  cancel-in-progress: true
  group: ${{github.workflow}}-${{github.ref}}

on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/ci-utils.yml"
      - "utils/**"
      - "foundry.base.toml"
      - "package.json"
  push:
    branches:
      - "main"
      - "staging"
    paths:
      - ".github/workflows/ci-utils.yml"
      - "utils/**"
      - "foundry.base.toml"
      - "package.json"

jobs:
  check:
    uses: "sablier-labs/gha-utils/.github/workflows/full-check.yml@main"
    with:
      foundry-version: "stable"

  build:
    uses: "sablier-labs/gha-utils/.github/workflows/forge-build.yml@main"
    with:
      foundry-version: "stable"
      foundry-profiles: "default"

  test-bulloak:
    needs: ["check", "build"]
    if: needs.build.outputs.cache-status != 'primary'
    uses: "sablier-labs/gha-utils/.github/workflows/bulloak-check.yml@main"
    with:
      skip-modifiers: true
      test-dir: "tests"

  test-integration:
    needs: ["check", "build"]
    if: needs.build.outputs.cache-status != 'primary'
    uses: "sablier-labs/gha-utils/.github/workflows/forge-test.yml@main"
    with:
      foundry-fuzz-runs: 2000
      foundry-version: "stable"
      match-path: "utils/tests/integration/**/*.sol"
      name: "Integration tests"

  test-invariant:
    needs: ["check", "build"]
    if: needs.build.outputs.cache-status != 'primary'
    uses: "sablier-labs/gha-utils/.github/workflows/forge-test.yml@main"
    with:
      foundry-invariant-depth: 100
      foundry-invariant-runs: 300
      foundry-version: "stable"
      match-path: "utils/tests/invariant/**/*.sol"
      name: "Invariant tests"

  coverage:
    needs: ["check", "build"]
    if: needs.build.outputs.cache-status != 'primary'
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    uses: "sablier-labs/gha-utils/.github/workflows/forge-coverage.yml@main"
    with:
      foundry-version: "stable"
      match-path: "utils/tests/integration/**/*.sol"
