name: "CI: Utils"
run-name: "CI Utils :: ${{ github.event.head_commit.message || github.event.pull_request.title }}"

concurrency:
  cancel-in-progress: true
  group: ${{github.workflow}}-${{github.ref}}

on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/ci-utils.yml"
      - ".github/workflows/ci-module.yml"
      - "utils/**"
      - "foundry.base.toml"
      - "package.json"
  push:
    branches:
      - "main"
      - "staging"
    paths:
      - ".github/workflows/ci-utils.yml"
      - ".github/workflows/ci-module.yml"
      - "utils/**"
      - "foundry.base.toml"
      - "package.json"

jobs:
  ci:
    uses: "./.github/workflows/ci-module.yml"
    with:
      module: "utils"
      foundry-profiles: "default"
      run-integration: true
      run-invariant: true
      invariant-runs: 300
      coverage-match-path: "utils/tests/integration/**/*.sol"
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
