name: "CI"

concurrency:
  cancel-in-progress: true
  group: ${{github.workflow}}-${{github.ref}}

env:
  FOUNDRY_DISABLE_NIGHTLY_WARNING: "true"

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "staging"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: sablier-labs/devkit/actions/setup@main
        with:
          frozen-lockfile: false
          package-manager: bun
      - uses: foundry-rs/foundry-toolchain@v1
        with:
          version: "nightly"

      - name: Run all code checks
        run: just full-check

  test-unit:
    needs: check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workspace: [airdrops, lockup]
    steps:
      - uses: actions/checkout@v5
      - uses: foundry-rs/foundry-toolchain@v1
        with:
          version: "nightly"
      - uses: oven-sh/setup-bun@v2
      - run: bun install

      - name: Build contracts
        run: |
          just build ${{ matrix.workspace }} optimized

      - name: Run unit tests
        env:
          FOUNDRY_FUZZ_RUNS: 2000
          FOUNDRY_PROFILE: test-optimized
        run: | #shell
          forge test \
            --match-path "tests/unit/**/*.sol" \
            --root ${{ matrix.workspace }}

  test-integration:
    needs: check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workspace: [airdrops, flow, lockup, utils]
    steps:
      - uses: actions/checkout@v5
      - uses: foundry-rs/foundry-toolchain@v1
        with:
          version: "nightly"
      - uses: oven-sh/setup-bun@v2
      - run: bun install

      - name: Build contracts
        env:
          FOUNDRY_PROFILE: optimized
        run: |
          just build ${{ matrix.workspace }}

      - name: Run integration tests
        env:
          FOUNDRY_FUZZ_RUNS: 2000
          FOUNDRY_PROFILE: test-optimized
        run: | #shell
          forge test \
            --match-path "tests/integration/**/*.sol" \
            --root ${{ matrix.workspace }}

  test-invariant:
    needs: check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workspace: [flow, lockup, utils]
    steps:
      - uses: actions/checkout@v5
      - uses: foundry-rs/foundry-toolchain@v1
        with:
          version: "nightly"
      - uses: oven-sh/setup-bun@v2
      - run: bun install

      - name: Build contracts
        env:
          FOUNDRY_PROFILE: optimized
        run: |
          just build ${{ matrix.workspace }}

      - name: Run invariant tests
        env:
          FOUNDRY_PROFILE: test-optimized
        run: | #shell
          forge test \
            --match-path "tests/invariant/**/*.sol" \
            --root ${{ matrix.workspace }}
