name: "CI"

concurrency:
  cancel-in-progress: true
  group: ${{github.workflow}}-${{github.ref}}

env:
  FOUNDRY_DISABLE_NIGHTLY_WARNING: "true"

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "staging"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: sablier-labs/devkit/actions/setup@main
        with:
          frozen-lockfile: false
          package-manager: bun
      - uses: foundry-rs/foundry-toolchain@v1
        with:
          version: "nightly"

      - name: Run all code checks
        run: just full-check

  test:
    needs: check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # ---------------------------------------------------------------------------- #
          #                                     Unit                                     #
          # ---------------------------------------------------------------------------- #
          - workspace: airdrops
            fuzz-runs: 2000
            test-type: unit
          - workspace: lockup
            fuzz-runs: 2000
            test-type: unit
          # ---------------------------------------------------------------------------- #
          #                                 INTEGRATION                                  #
          # ---------------------------------------------------------------------------- #
          - workspace: airdrops
            fuzz-runs: 2000
            test-type: integration
          - workspace: flow
            fuzz-runs: 2000
            test-type: integration
          - workspace: lockup
            fuzz-runs: 2000
            test-type: integration
          - workspace: utils
            fuzz-runs: 2000
            test-type: integration
          # ---------------------------------------------------------------------------- #
          #                                   INVARIANT                                  #
          # ---------------------------------------------------------------------------- #
          - workspace: flow
            test-type: invariant
          - workspace: lockup
            test-type: invariant
          - workspace: utils
            test-type: invariant
    steps:
      - uses: actions/checkout@v5
      - uses: foundry-rs/foundry-toolchain@v1
        with:
          version: "nightly"
      - uses: oven-sh/setup-bun@v2
      - run: bun install

      - name: "Cache Foundry artifacts and Node.js dependencies"
        id: "cache-step"
        uses: "sablier-labs/gha-utils/.github/actions/evm-cache@main"
        with:
          cache-path: |
            node_modules
            ${{ matrix.workspace }}/cache
            ${{ matrix.workspace }}/out-optimized

      - name: Build contracts
        if: steps.cache-step.outputs.cache-status != 'primary'
        env:
          FOUNDRY_PROFILE: optimized
        run: |
          forge build --root ${{ matrix.workspace }}

      - name: Run tests
        if: steps.cache-step.outputs.cache-status != 'primary'
        env:
          FOUNDRY_FUZZ_RUNS: ${{ matrix.fuzz-runs || '' }}
          FOUNDRY_PROFILE: test-optimized
        run: | #shell
          forge test \
            --match-path "tests/${{ matrix.test-type }}/**/*.sol" \
            --root ${{ matrix.workspace }}
